version: "3.9"

services:
  app:
    container_name: app
    build: ./Software
    expose:
      - "80"
  server:
    container_name: nginx
    build: ./nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/project.com.conf:/etc/nginx/conf.d/project.com.conf
    depends_on:
      - app
