version: "3.9"

services:
  app:
    container_name: app
    build:
      context: ./WebService
      dockerfile: app.Dockerfile
    expose:
      - "80"
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/app.com.conf:/etc/nginx/conf.d/app.com.conf
    depends_on:
      - app
