version: "3.9"

services:
  app:
    container_name: app
    build:
      context: ./Software
      dockerfile: app.dockerfile
    expose:
      - "80"
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/project.com.conf:/etc/nginx/conf.d/project.com.conf
    depends_on:
      - app
